rapidsai/jupyterlab-nvdashboard

- .travis.yml
Looks like we have to run `jlpm build` to get the typescript to compile, which means we need Jupyter Lab. Probably easiest to install with conda so adding that here.
> Add conda and build with jlpm

- jupyterlab_nvdashboard/apps/gpu.py
This PR applies black formatting to `jupyterlab_nvdashboard/apps/gpu.py`, and addresses [issue #7](https://github.com/jacobtomlinson/jupyterlab-nvdashboard/issues/7).  That is, the "Total PCI Throughput" plot for the "GPU Resources" dashboard now has a dynamic y-axis scale.
While addressing this issue, I also noticed that the stand-alone "PCI Throughput" dashboard had the maximum set to 5000 MB/s.  I tried making this scale dynamic as well, but didn't like the way it looked.  I will probably raise a new issue to discuss the best way to deal with this.
> Making "Total PCI Throughput" y-axis have a dynamic scale

- jupyterlab_nvdashboard/apps/gpu.py
- jupyterlab_nvdashboard/server.py
These changes add "NVLink Throughput" and "NVLink Timeline" dashboares.   This addresses [#13](https://github.com/jacobtomlinson/jupyterlab-nvdashboard/issues/13), but requires pynvml 8.0.2+ (both conda and PyPI packages are available).
**Example** (deep learning training on 2-GPUs):
**Note 1**:  The "NVLink Throughput" axis range is set to the theoretical maximum for a single GPU (which can be quite large).  The "NVLink Timeline" axis, however, is adaptive.
**Note 2**:  The formatting/naming of the existing dashboards was also modfied a bit.  For example, I am changing "PCI" to "PCIe", and using consistent "Byte" formatting for labels/titles.
> Adding NVLink dashboards

- jupyterlab_nvdashboard/server.py
- setup.py
Moved the standalone server startup into a function and then added an entry point so that the function can be invoked with the command `nvdashboard` from the command line.
This should make things easier to run when not using it in Jupyter Lab.
> Add command line util for standalone server

- setup.py
Follows the naming convention for the license according to SPDX. Makes it easier for users, auditors, and tooling to identify the type of license.
> Use SPDX `license` metadata

- jupyterlab_nvdashboard/__init__.py
Should fix `could not start nvdashboard in time` error by extending the timeout that Jupyter gives the process to start.
Closes #31
> Extend startup timeout

- ci/cpu/build.sh
This PR updates the version of `npm` used in CI. This fixes an ambiguous error that was being throw in CI when using `npm version` ([link to error log](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/jupyterlab-nvdashboard/job/branches/job/jupyterlab-nvdashboard-cpu-branch-build/25/console)). Ultimately, it seems that updating to the latest `npm` version make the error go away.
The screenshots below show the results of my local testing and verification for this problem. 
**CI Version. Error**
**Updated Version. No error**
> Update npm version in CI

- jupyterlab_nvdashboard/__init__.py
Fixes #98. Tested locally. @ian-r-rose 's [comment](https://github.com/rapidsai/jupyterlab-nvdashboard/issues/98#issuecomment-847925377) helped in quickly finding the problem. `jupyterlab-server-proxy` has documentation available on the automatically generated [launcher entry](https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html#launcher-entry).
> Disabled automatic launcher entry

- conda/recipes/jupyterlab-nvdashboard/meta.yaml
This PR adds a version specification to `nodejs` in the `conda` recipe. The latest `nodejs` package version (`16.10.0`) seems to cause build errors for `jupyterlab-nvdashboard`.
> Add `nodejs` version specification to conda recipe

- conda/recipes/jupyterlab-nvdashboard/meta.yaml
Due to an `openssl` upgrade in the latest `NodeJs` version, we need to enable the legacy `openssl` provider to fix the build until `jupyterlab` publish a new version with a fix for this
> Fix openssl build issue

- jupyterlab_nvdashboard/apps/gpu.py
- jupyterlab_nvdashboard/server.py
- src/index.ts
We plan to deploy jupyterlab-nvdashboard on heterogenous HPC clusters with that nodes that do not all have GPUs, nor `libnvidia-ml.so.1` installed. This PR makes sure the dashboard that are not related to GPUs can be still be used when pynvml fails to initialize because CUDA drivers are not installed.
This is done by catching `pynvml.nvml.NVMLError_LibraryNotFound` in `gpu.py`. If the exception is raised, we consider that are no GPUs and set `ngpus = 0`. It would be valuable to log a warning here. I have not added any warning as nvdashboard currently never print nor log anything.
When comes the routes definition, if ngpus is greater than 0, we defines the routes related to GPU apps.
> Make nvdashboard usable even when "NVML Shared Library Not Found"

- conda/recipes/jupyterlab-nvdashboard/meta.yaml
With the PR below merged, we no longer set the `CUDAHOSTCXX` variable in any of our CI images. This PR cleans up some references to `CUDAHOSTCXX`.
- https://github.com/rapidsai/gpuci-build-environment/pull/265
I don't think these variables were relevant to `jupyterlab-nvdashboard` anyway since it's just a JupyterLab extension.
> Remove compiler variables

- jupyterlab_nvdashboard/apps/gpu.py
- requirements.txt
Various of the NVML API calls to query for NVLink status have been deprecated since the CUDA 11.0 release. Resetting counters is also not allowed anymore.
New results:
Fixes #28, #114
> Update deprecated NVML API calls for NVLink query

- README.md
This PR updates the README to better explain what NVDashboard is (copying from https://developer.nvidia.com/blog/gpu-dashboards-in-jupyter-lab/ ) and to include the existing demo gif in the repository root.
Closes https://github.com/rapidsai/jupyterlab-nvdashboard/issues/142
> Update README with NVDashboard summary and demo gif

- ci/cpu/build.sh
- ci/gpu/build.sh
- conda/recipes/jupyterlab-nvdashboard/meta.yaml
This PR moves the date string from the version to the build string for conda recipes in this repository.
This is necessary to ensure that the conda packages resulting from PR builds can be installed in the same environment as nightly conda packages, which is useful for testing purposes.
Additionally, this prevents a bug from occurring where the Python builds fail because the date string it computes is different than the one computed by the C++ build, therefore causing the Python build to search for a C++ build artifact that doesn't exist.
xref: https://github.com/rapidsai/rmm/pull/1195
> Move date to build string in `conda` recipe

- jupyterlab_nvdashboard/server.py
This PR fixes an issue caused when running jupyterlab via docker containers (exposing only a few ports), leading to blank front-end screen, even when the bokeh server runs fine. 
The bokeh server is started in the background on some random port (default 8000), but is accessed in jupyterlab via jupyter-server-proxy, i.e., `localhost:8888/proxy/{port}/{resources}` . In a local env, we have access to {port} directly via localhost:{port}, that's why the extension works. In containers, that random port isn't exposed, so we have to make sure the resources are accessed (front-end bokeh resources) via the proxy urls, but they are being accessed directly, as seen in the screenshot below.
Hence the blank screen, due to no bokeh.js being available on the front-end.
Loading front-end resources via …
> fix docker container blank screen issue

- src/charts/GpuResourceChart.tsx
- src/charts/MachineResourceChart.tsx
- src/launchWidget.tsx
- style/base.css
This PR fixes #178 while also adding minimum size constraints(`[25vw, 25vw]`) to all plots, and a slightly larger minHeight(`45vh`) for timeseries plot to make sure the seekbar is always visible since we got rid of the vertical scroll.
cc @jacobtomlinson 
Preview: (No scrolls visible anymore)
> add minimum size constraints to all widgets and remove vertical scroll

- package.json
- schema/config.json
- src/assets/constants.ts
- src/assets/hooks.ts
- src/assets/interfaces.ts
- src/charts/GpuMemoryChart.tsx
- src/charts/GpuResourceChart.tsx
- src/charts/GpuUtilizationChart.tsx
- src/charts/MachineResourceChart.tsx
- src/charts/NvLinkThroughputChart.tsx
- src/charts/NvLinkTimelineChart.tsx
- src/charts/PciThroughputChart.tsx
- src/index.ts
- src/launchWidget.tsx
- style/base.css
- yarn.lock
Implements #179. Also added the ability to set a custom refresh speed via jupyterlab settings. The settings once set will be global across the jupyterlab session, even when you restart the jupyterlab server. The setting also has type checking along with a minimum value of 1ms.
cc @jacobtomlinson
> add dynamic updateFrequency via settingsRegistry

- .github/ops-bot.yaml
This PR enables the ForwardMerger [ops-bot](https://github.com/rapidsai/ops-bot) plugin.
> enable forward merger plugin

- ci/check_style.sh
- ci/test_python.sh
conda dropped support for the `--force` flag to `conda env create`. This changes that flag name to `--yes`.
See https://github.com/conda/conda/blob/main/CHANGELOG.md#2430-2024-03-12 and https://github.com/rapidsai/miniforge-cuda/pull/63 for more info.
> Use `conda env create --yes` instead of `--force`

- jupyterlab_nvdashboard/apps/utils.py
- jupyterlab_nvdashboard/tests/test_cpu_handlers.py
- jupyterlab_nvdashboard/tests/test_gpu_handlers.py
This PR adds authentication to WS requests, using the inbuilt `self.current_user` method in jupyter_handler, without which the ws requests will not be served.
> Add authentication to ws requests

- .pre-commit-config.yaml
- ci/check_style.sh
- ci/test_python.sh
Contributes to https://github.com/rapidsai/dependency-file-generator/issues/89
Resolves this warning I see in build and test CI jobs, coming from `rapids-dependency-file-generator`.
> /opt/conda/lib/python3.9/site-packages/rapids_dependency_file_generator/cli.py:98: UserWarning: The use of --file_key is deprecated. Use -f or --file-key instead.
> resolve file_key deprecation warning from rapids-dependency-file-generator

- .github/workflows/pr.yaml
- .pre-commit-config.yaml
- ci/build_wheel.sh
- ci/test_wheel.sh
- jupyterlab_nvdashboard/apps/gpu.py
- jupyterlab_nvdashboard/tests/test_cpu_handlers.py
- jupyterlab_nvdashboard/tests/test_gpu_handlers.py
We recently observed some issues with Python 3.12 + older `flake8` versions across RAPIDS: https://github.com/rapidsai/build-planning/issues/101.
This proposes updating all the pre-commit hooks in this repo (`pre-commit autoupdate`) to avoid such issues the next time someone comes to push new commits here.
While doing this, I also discovered that wheel CI here was broken by https://github.com/rapidsai/shared-workflows/pull/213 (see https://github.com/rapidsai/jupyterlab-nvdashboard/pull/205#discussion_r1767661424). This fixes that as well.
> update pre-commit hook versions, mark wheels as pure python

- style/icons/expansion-card.svg
Changes the `expansion-card.svg` code from `jp-icon0` class to `jp-icon3` which is more appropriate for sidebar/window icons in JupyterLab design style.
Fixes https://github.com/rapidsai/jupyterlab-nvdashboard/issues/199
| Before | After |
| -- | -- |
| ![image](https://github.com/rapidsai/jupyterlab-nvdashboard/assets/5832902/0d660026-05ff-46d2-b3f2-82018a59c596) |  ![image](https://github.com/rapidsai/jupyterlab-nvdashboard/assets/5832902/86817c02-751d-45c5-aeed-032a4700a31e) |
| Before | After |
| -- | -- |
| ![image](https://github.com/rapidsai/jupyterlab-nvdashboard/assets/5832902/8ace1694-a9d8-4053-8047-233f26e9362c) | ![image](https://github.com/rapidsai/jupyterlab-nvdashboard/assets/5832902/bccf43fa-5f51-4dcd-8713-1299864ccd11) |
| Before | After |
| -- | -- |
| …
> Harmonize the icon color with the standard color

- ci/build_wheel.sh
- ci/validate_wheel.sh
- pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/110
Proposes adding 2 types of validation on wheels in CI, to ensure we continue to produce wheels that are suitable for PyPI.
* checks on wheel size (compressed),
- *to be sure they're under PyPI limits*
- *and to prompt discussion on PRs that significantly increase wheel sizes*
* checks on README formatting
- *to ensure they'll render properly as the PyPI project homepages*
- *e.g. like how https://github.com/scikit-learn/scikit-learn/blob/main/README.rst becomes https://pypi.org/project/scikit-learn/*
> enforce wheel size limits, README formatting in CI
