src/index.ts

Set the window icon to be the same as the sidebar icon.
Closes #3.

Set window icon

---

LICENSE.txt
setup.py

See https://github.com/ian-r-rose/jupyterlab-bokeh-server/issues/9
See https://github.com/ian-r-rose/jupyterlab-bokeh-server/issues/10

Add license file from upstream

---

MANIFEST.in
setup.cfg

Add license file to package and wheels.
Closes #16 
cc @jakirkham

Add license to packages

---

src/dashboard.tsx

Add baseURL to dashboard urls

---

ci/cpu/build.sh
ci/cpu/upload-packages.sh
setup.py

Adds the pip package back into the build process.

[REVIEW] Add pip building

---

ci/checks/style.sh
ci/cpu/build.sh
ci/cpu/upload-packages.sh
ci/gpu/build.sh
ci/releases/update-version.sh
conda/recipes/jupyterlab-nvdashboard/meta.yaml
jupyterlab_nvdashboard/server.py
setup.py

Only critical/hotfix level issues should be merged into `branch-0.2` until release (merging of this PR).
- Update documentation
- Allow testing for the new release
- Enable a means to merge `branch-0.2` into `master` for the release

[RELEASE] jupyterlab-nvdashboard v0.2

---

.travis.yml
conda/recipes/jupyterlab-nvdashboard/meta.yaml
requirements.txt

Stopgap for issue ( https://github.com/rapidsai/jupyterlab-nvdashboard/issues/49 )

Require Bokeh 1.*

---

README.md

Some users are having issues as we do not currently support Windows. Adding a notice to make it clear.

Add notice about no windows support

---

package.json
src/dashboard.tsx
yarn.lock

Add support for Jupyter Lab 2.0

---

requirements.txt

Some local testing seems to show that no further changes are needed.
Closes #66

Bump minimum Bokeh to 2.1

---

conda/recipes/jupyterlab-nvdashboard/meta.yaml

Removed some unnecessary build requirements and added additional run requirements (bokeh 2.1+, jupyterlab, and nodejs).
I tested the recipe locally with conda build and it seems to be working fine when installed to a new environment.

Updated the meta.yaml to use Bokeh 2.1+ and tweaked some other requirements

---

ci/release/update-version.sh
conda/recipes/jupyterlab-nvdashboard/meta.yaml
package.json
requirements.txt
setup.py
yarn.lock

This PR syncs the new `main` branch with the existing `master` branch.

[skip-ci] Sync main with master

---

ci/cpu/build.sh
ci/cpu/upload.sh

This PR updates the CI scripts in anticipation of the next release.

Update ci scripts

---

conda/recipes/jupyterlab-nvdashboard/meta.yaml

Pass compiler environment variables to conda python build

Pass compiler environment variables to conda python build

---

style/expansion-card-variant-dark.svg
style/expansion-card-variant-light.svg

Decided to redraw the little GPU icon to look a little more like an A6000.

Updated GPU icon

---

jupyterlab_nvdashboard/apps/cpu.py
jupyterlab_nvdashboard/apps/gpu.py

Reverts rapidsai/jupyterlab-nvdashboard#132

Revert "Plot with legend_label option to remove BokehDeprecationWarnings"

---

README.md
ci/build_python.sh

This PR fixes the build_python script which fixes the incorrect build issue in conda-build workflow.
Also added updated install instructions for both conda and pypi install.

fix build_python ci script

---

.github/workflows/build.yaml
.github/workflows/pr.yaml

Update shared-workflows version to 24.10

Update shared-workflows version

---

schema/config.json

Fixes #200
| Before | After |
|--|--|
| ![image](https://github.com/rapidsai/jupyterlab-nvdashboard/assets/5832902/5652957e-5321-4642-adf1-088353feb752) | ![image](https://github.com/rapidsai/jupyterlab-nvdashboard/assets/5832902/955ef962-5031-42f9-ae7f-cb89feaba836) |

Shorten settings title, add icon

---

.github/workflows/build.yaml
.github/workflows/pr.yaml

https://github.com/rapidsai/jupyterlab-nvdashboard/pull/212#issuecomment-2532687426

fix old version refs

---

.github/workflows/build.yaml

Publish release builds to PyPI automatically.

Publish to PyPI automatically
